auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 0
  log_level: info

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m

ruler:
  enable_api: true
  alertmanager_url: http://alertmanager:9093
  storage:
    type: local
    local:
      directory: /loki/rules
  ring:
    kvstore:
      store: inmemory

limits_config:
  max_streams_per_user: 10000
